### ISSUE TITLE
The content of the page should be in a container.

### ISSUE THREAD

**Issue by jecisc** [estebanlm/worklog#6]
I have a horizontal scrollbar on the log page (http://log.smallworks.eu/web) because the rows are not in a tbsContainer. 

It's not that important but easy to fix :)

I don't know if the template html is in this project but I don't have time to check.

**Comment by jecisc** [comment]
Oh, nevermind. Already corrected in 0d3b9f28d5b3ac9aca14bffe9d4ccff893d6b4ea

**Comment by estebanlm** [comment]
yes... just I didn't updated my site :P
